services:
  db:
    image: postgres:18
    container_name: pokemon_db
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
