"""add RevokedToken table

Revision ID: 14dd4699db1a
Revises: c6a640899f13
Create Date: 2026-06-25 14:21:28.677881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "14dd4699db1a"
down_revision: Union[str, Sequence[str], None] = "c6a640899f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revokedtoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revokedtoken_token"), "revokedtoken", ["token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_revokedtoken_token"), table_name="revokedtoken")
    op.drop_table("revokedtoken")
    # ### end Alembic commands ###
