"""set null on trainer delete

Revision ID: 42ceb794a720
Revises: c7ffcc7156f5
Create Date: 2026-06-16 15:53:03.995666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ceb794a720'
down_revision: Union[str, Sequence[str], None] = 'c7ffcc7156f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pokemon_trainer_id_fkey'), 'pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'pokemon', 'trainer', ['trainer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.create_foreign_key(op.f('pokemon_trainer_id_fkey'), 'pokemon', 'trainer', ['trainer_id'], ['id'])
    # ### end Alembic commands ###
