"""add capa

Revision ID: 43393b208a23
Revises: ad26d5f8bc45
Create Date: 2026-06-08 15:30:34.289316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "43393b208a23"
down_revision: Union[str, Sequence[str], None] = "ad26d5f8bc45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pokemon", sa.Column("capa", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon", "capa")
    # ### end Alembic commands ###
