"""add pokemon creator

Revision ID: 90e0ceadf979
Revises: c7c8d4406b3c
Create Date: 2026-06-24 12:48:15.246963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e0ceadf979'
down_revision: Union[str, Sequence[str], None] = 'c7c8d4406b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'created_by')
    # ### end Alembic commands ###
