"""add level

Revision ID: a975b3d1537b
Revises: 9058af900d85
Create Date: 2026-06-08 14:57:27.877371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a975b3d1537b"
down_revision: Union[str, Sequence[str], None] = "9058af900d85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pokemon", sa.Column("level", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon", "level")
    # ### end Alembic commands ###
