"""add trainer relation

Revision ID: c7ffcc7156f5
Revises: 43393b208a23
Create Date: 2026-06-09 15:20:05.943685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c7ffcc7156f5"
down_revision: Union[str, Sequence[str], None] = "43393b208a23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trainer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("pokemon", sa.Column("trainer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "pokemon", "trainer", ["trainer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pokemon", type_="foreignkey")
    op.drop_column("pokemon", "trainer_id")
    op.drop_table("trainer")
    # ### end Alembic commands ###
