"""add attack

Revision ID: e89faff79c8b
Revises: a975b3d1537b
Create Date: 2026-06-08 14:59:29.315324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e89faff79c8b"
down_revision: Union[str, Sequence[str], None] = "a975b3d1537b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pokemon",
        sa.Column("attack", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon", "attack")
    # ### end Alembic commands ###
